spring.application.name=multi-datasource
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# -------------------------
# PRIMARY DATASOURCE
# -------------------------
spring.datasource.primary.url=jdbc:mysql://localhost:3306/epayjsc
spring.datasource.primary.username=root
spring.datasource.primary.password=password
spring.datasource.primary.driver-class-name=com.mysql.cj.jdbc.Driver

# -------------------------
# SECONDARY DATASOURCE
# -------------------------
spring.datasource.secondary.url=jdbc:mysql://localhost:3306/springboot
spring.datasource.secondary.username=root
spring.datasource.secondary.password=password

spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver
