spring:
  application:
    name: bankos
  datasource:
    url: jdbc:postgresql://163.223.8.60:5432/bankos
    username: bankos_user
    password: +O3iXlw+QLqqvrhAlSTeaA3SD66o0udx/dbnZfOYPWM=
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 163.223.8.60
      port: 6379
      password: "R3d!s#B@nk0s2026$"