KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_payment-svc="payment-secret"
    user_outbox-svc="outbox-secret"
    user_notification-svc="notification-secret"
    user_audit-svc="audit-secret"
    user_saga-svc="saga-secret";
};